server:
  port: 10141

spring:
  application:
    name: Order Management Service
  main:
    banner-mode: "off"
  datasource:
    hikari:
      axon-master:
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/axon_event_store?zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234qwer
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTestQuery: SELECT 1
        connectionTimeout: 30000
        maximumPoolSize: 10
      projection-write:
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/order_write?zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234qwer
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTestQuery: SELECT 1
        connectionTimeout: 30000
        maximumPoolSize: 10
      projection-read:
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/order_read?zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234qwer
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTestQuery: SELECT 1
        connectionTimeout: 30000
        maximumPoolSize: 10
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect

axon:
  serializer:
    events: jackson