server:
  port: 10141

logging:
  level:
    com.zaxxer.hikari.pool.*: debug
    #org.springframework.web: debug

spring:
  application:
    name: Order Management Service
  main:
    banner-mode: "off"
  datasource:
    hikari:
      dataSourceProperties:
        fastConnectionFailoverEnabled: true
      leak-detection-threshold: 5000
      axon-master:
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/order_axon_event_store?zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234qwer
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTestQuery: SELECT 1
        connectionTimeout: 10000
        maximumPoolSize: 15
      projection-master:
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/order_master?zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234qwer
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTestQuery: SELECT 1
        connectionTimeout: 10000
        maximumPoolSize: 10
      projection-slave:
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/order_slave?zeroDateTimeBehavior=convertToNull
        username: root
        password: 1234qwer
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTestQuery: SELECT 1
        connectionTimeout: 10000
        maximumPoolSize: 10
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
axon:
  serializer:
    events: jackson